# Generated by Django 4.2.3 on 2023-07-27 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0007_alter_news_date_alter_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 19, 25, 26, 655821)),
        ),
    ]
