# Generated by Django 4.2.3 on 2023-07-30 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0011_alter_news_date_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 18, 54, 55, 586468)),
        ),
    ]
